# Generated by Django 4.2.3 on 2023-08-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(height_field=80, upload_to='images/', width_field=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Page1.category')),
            ],
        ),
    ]
