# Generated by Django 4.2.3 on 2023-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page1', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
